/**
 * The street's sprite data, copied row-for-row from the two prototype
 * sheets — prototypes/pixel-fronts.html and prototypes/pixel-fleet.html.
 * The sheets stay the place the art is argued about; this file is the
 * shipped copy, and a change to a sprite belongs on the sheet first.
 *
 * Generated 2026-08-29. Data only: grids of palette letters, and the
 * palettes those letters index. The renderer in street.ts owns the rest.
 */

export interface FrontSprite {
  shell: keyof typeof SHELLS;
  sign: string;
  rows: string[];
}

export interface CarSprite {
  /** Cars with a livery of their own ignore the paint they are offered. */
  fixed: string | null;
  rows: string[];
}

export const SHELLS: Record<string, [string, string, string]> = {
  "brick": [
    "#2a1a16",
    "#4a2b22",
    "#6b3d2e"
  ],
  "stucco": [
    "#3b3428",
    "#5c5443",
    "#8a7f66"
  ],
  "stone": [
    "#26221d",
    "#3d3830",
    "#5c5449"
  ],
  "clapboard": [
    "#22261f",
    "#363d2f",
    "#4f5943"
  ]
};

export const FRONT_BASE: Record<string, string> = {
  "0": "#0c0a09",
  "d": "#1a212b",
  "e": "#7d6720",
  "g": "#1c1713",
  "h": "#c2352b",
  "i": "#ded3bc",
  "j": "#6d1b16",
  "k": "#ded3bc",
  "m": "#3b2519",
  "n": "#5f3d27",
  "p": "#3d3d42",
  "q": "#524d46",
  "r": "#dd5347",
  "y": "#c9a227",
  "z": "#7593a8",
  "s": "#241d18",
  "t": "#332a22",
  "w": "#ded3bc"
};

export const CAR_PAINTS: Record<string, [string, string, string]> = {
  "black": [
    "#0f0f11",
    "#1c1c20",
    "#2e2e34"
  ],
  "maroon": [
    "#2a0f0e",
    "#4a1a17",
    "#6d2622"
  ],
  "candy": [
    "#3d0b09",
    "#6b1310",
    "#a5251b"
  ],
  "copper": [
    "#2c1608",
    "#4d2a10",
    "#7a441c"
  ],
  "gold": [
    "#2e2109",
    "#544012",
    "#8a6a22"
  ],
  "cream": [
    "#5c5443",
    "#8a7f66",
    "#b3a68a"
  ],
  "white": [
    "#4a4741",
    "#7a766d",
    "#b3ada0"
  ],
  "silver": [
    "#2b2e31",
    "#4a4f54",
    "#787f86"
  ],
  "primer": [
    "#2a2724",
    "#3d3934",
    "#524d46"
  ],
  "olive": [
    "#1e2417",
    "#333d24",
    "#4f6337"
  ],
  "jade": [
    "#0d2019",
    "#173a2c",
    "#255a44"
  ],
  "teal": [
    "#0c2027",
    "#143741",
    "#1f5561"
  ],
  "blue": [
    "#131b26",
    "#22303f",
    "#37485c"
  ],
  "plum": [
    "#22101f",
    "#3b1a34",
    "#5a2a4e"
  ]
};

export const CAR_FIXED: Record<string, string> = {
  "0": "#0c0a09",
  "d": "#232c38",
  "e": "#7593a8",
  "f": "#9c9083",
  "F": "#ded3bc",
  "t": "#15110e",
  "T": "#3d3d42",
  "r": "#c2352b",
  "i": "#332a22",
  "w": "#ded3bc",
  "W": "#8a8578",
  "p": "#524d46",
  "q": "#1c1713",
  "k": "#0c0a09",
  "n": "#3b2519",
  "m": "#5f3d27",
  "M": "#855838"
};

export const FRONT_SPRITES: Record<string, FrontSprite> = {
  real_estate: {
    shell: 'stucco',
    sign: '#4a443a',
    rows: [
      '................................................',
      '................................................',
      '................................................',
      '000000000000000000000000000000000000000000000000',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbabbbbbbbbbbabbbbbbbbbbabbbbbbbbbbabbbbbbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbbaaaaaaaabbbbbaaaaaaaabbbbbaaaaaaaabbbbbba',
      'abbbbbbadddaddabbbbbadddaddabbbbbadddaddabbbbbba',
      'abbbbbbadddaddabbbbbadddaddabbbbbadddaddabbbbbba',
      'aaaaaaaadddaddaaaaaaadddaddaaaaaaadddaddaaaaaaaa',
      'abbbbbaadddaddabbabbadddaddaabbbbadddaddabbbbbba',
      'abbbbbaadddaddabbabbadddaddaabbbbadddaddabbbbbba',
      'abbbbbaadddaddabbabbadddaddaabbbbadddaddabbbbbba',
      'aaaaaaaadddaddaaaaaaadddaddaaaaaaadddaddaaaaaaaa',
      'abbbbbbaaaaaaaabbbbbaaaaaaaabbbbbaaaaaaaabbbbbba',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'gggggggggggggggggggggggggggggggggggggggggggggggg',
      'ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
      'ghhhhhiihhiihhiihhiihhiihhiihhiihhiihhiihhhhhhhg',
      'ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
      'gggggggggggggggggggggggggggggggggggggggggggggggg',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaadddddddddddddddddaaaaammmmmmmmmmmaaaaaaaaaaa',
      'aaaadddddddddddddddddaaaaammdddddddmmaaaaaaaaaaa',
      'aaaadddddddddddddddddaaaaammdddddddmmaaaaaaaaaaa',
      'aaaadddddddddddddddddaaaaammdddddddmmaaaaaaaaaaa',
      'aaaadddddddddddddddddaaaaammdddddddmmaaaaaaaaaaa',
      'aaaadddddddddddddddddaaaaammdddddddmmaaaaaaaaaaa',
      'aaaadddddddddddddddddaaaaammmmmmmmmmmaaaaaaaaaaa',
      'aaaadddddddddddddddddaaaaammmmmmmmmmmaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'tttttttttttttttttttttttttttttttttttttttttttttttt',
      'ssssssssssssssssssssssssssssssssssssssssssssssss',
      '000000000000000000000000000000000000000000000000',
    ],
  },
  restaurant: {
    shell: 'brick',
    sign: '#6d1b16',
    rows: [
      '................................................',
      '................................................',
      '................................................',
      '000000000000000000000000000000000000000000000000',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbbbbbbaaaaaaaabbbbbbbbbaaaaaaaabbbbbbbbbbba',
      'abbbbbbbbbbaaaaaaaabbbbbbbbbaaaaaaaabbbbbbbbbbba',
      'aaaaaaaaaaaadddaddaaaaaaaaaaadddaddaaaaaaaaaaaaa',
      'abbbbbbbbbbadddaddabbbbbbbbbadddaddabbbbbbbbbbba',
      'abbbbbbbbbbadddaddabbbbbbbbbadddaddabbbbbbbbbbba',
      'aaaaaaaaaaaadddaddaaaaaaaaaaadddaddaaaaaaaaaaaaa',
      'abbbbbbbbbbadddaddabbbbbbbbbadddaddabbbbbbbbbbba',
      'abbbbbbbbbbadddaddabbbbbbbbbadddaddabbbbbbbbbbba',
      'aaaaaaaaaaaadddaddaaaaaaaaaaadddaddaaaaaaaaaaaaa',
      'abbbbbbbbbbaaaaaaaabbbbbbbbbaaaaaaaabbbbbbbbbbba',
      'abbbbbggggggggggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'aaaaaaggaaaaggaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbbbbbbbggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'gggggggggggggggggggggggggggggggggggggggggggggggg',
      'ghhhhhhhhhhhgghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
      'ghhhhhiihhiiggiihhiihhiihhiihhiihhiihhiihhhhhhhg',
      'ghkkkjjjkgggggggggjjkkkjjjkkkjjjkkkjjjkkkjjjkkkg',
      'ggkkkjjjkghhhhhhhgjjkkkjjjkkkjjjkkkjjjkkkjjjkkkg',
      'aaaaaaaaaghhhhhhhgaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaddddddghhhhhhhgdddddddddddddaammmmmmmmmmmaaaa',
      'aaaddddddgggggggggdddddddddddddaammdddddddmmaaaa',
      'aaadddddddddddddaadddddddddddddaammdddddddmmaaaa',
      'aaadddddddddddddaadddddddddddddaammdddddddmmaaaa',
      'aaadddddddddddddaadddddddddddddaammdddddddwmaaaa',
      'aaadddddddddddddaadddddddddddddaammdddddddmmaaaa',
      'aaadddddddddddddaadddddddddddddaammmmmmmmmmmaaaa',
      'aaadddddddddddddaadddddddddddddaammmmmmmmmmmaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'tttttttttttttttttttttttttttttttttttttttttttttttt',
      'ssssssssssssssssssssssssssssssssssssssssssssssss',
      '000000000000000000000000000000000000000000000000',
    ],
  },
  hotel: {
    shell: 'stone',
    sign: '#5c5449',
    rows: [
      '...000...000...000...000...000...000...000......',
      '000ccc000ccc000ccc000ccc000ccc000ccc000ccc000000',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbaaaaaaaaabbabbaaaaaaaaabbbbaaaaaaaabbbbbba',
      'aaaaaaaadddaddaaaaaaadddaddaaaaaaadddaddaaaaaaaa',
      'abbbbbbadddaddabbbbbadddaddabbbbbadddaddabbbbbba',
      'abbbbbbadddaddabbbbbadddaddabbbbbadddaddabbbbbba',
      'abbbbbbadddaddabbbbbadddaddabbbbbadddaddabbbbbba',
      'aaaaaaaadddaddaaaaaaadddaddaaaaaaadddaddaaaaaaaa',
      'abbbbbaaaaaaaaabbabbaaaaaaaaabbbbaaaaaaaabbbbbba',
      'abbbbbaaaaaaaaabbabbaaaaaaaaabbbbaaaaaaaabbbbbba',
      'abbbbbaaaaaaaaabbabbaaaaaaaaabbbbaaaaaaaabbbbbba',
      'aaaaaaaadddaddaaaaaaadddaddaaaaaaadddaddaaaaaaaa',
      'abbbbbbadddaddabbbbbadddaddabbbbbadddaddabbbbbba',
      'abbbggggggggggabbbbbadddaddabbbbbadddaddabbbbbba',
      'abbbggbaddggddabbbbbadddaddabbbbbadddaddabbbbbba',
      'aaaaaaaaaaggaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbabbbggbbbbbabbbbbbbbbbabbbbbbbbbbabbbbbbba',
      'abbbbbabbbggbbbbbabbbbbbbbbbabbbbbbbbbbabbbbbbba',
      'abbbbbabbbggbbiiiiiiiiiiiiiiiiiiiibbbbbabbbbbbba',
      'aaaaaaagggggggggggggggggggggggggggaaaaaaaaaaaaaa',
      'abbbbbbghhhhhhhgggggggggggggggggggbbbbbbbbbbbbba',
      'abbbbbbghhhhhhhgbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'abbbbbbghhhhhhhgaaaaaaaaaaaaaaaabbbbbbbbbbbbbbba',
      'abbbbbbgggggggggammmmmmammmmmmmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbamdddddaddddddmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbamdddddaddddddmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbamdddddadddddwmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbamdddddaddddddmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbamdddddaddddddmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbammmmmmammmmmmmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbammmmmmammmmmmmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbammmmmmammmmmmmabbbbbbbbbbbbbbba',
      'tttttttttttttttttttttttttttttttttttttttttttttttt',
      'ssssssssssssssssssssssssssssssssssssssssssssssss',
      '000000000000000000000000000000000000000000000000',
    ],
  },
  auto_shop: {
    shell: 'brick',
    sign: '#3d5464',
    rows: [
      '................................................',
      '................................................',
      '................................................',
      '000000000000000000000000000000000000000000000000',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbbbbbaaaaaaaabbbbbbbbbbbbbbbbbbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbbbbbbbbbbbbbbbadddaddabbbbbbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbbbbbadddaddabbbbbbbbbbbbbbbbbbba',
      'aaaaaaaaaaaaaaaaaaaaadddaddaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbbbbbbbbbbbbbbbadddaddabbbbbbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbbbbbadddaddabbbbbbbbbbbbbbbbbbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'gggggggggggggggggggggggggggggggggggggggggggggggg',
      'ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
      'ghhhhhiihhiihhiihhiihhiihhiihhiihhiihhiihhhhhhhg',
      'ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
      'gggggggggggggggggggggggggggggggggggggggggggggggg',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaapppppppppppppppppppppppppppppaaammmmmmmmmaaa',
      'aaaaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqaaammdddddmmaaa',
      'aaaapppppppppppppppppppppppppppppaaammdddddmmaaa',
      'aaaaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqaaammdddddmmaaa',
      'aaaapppppppppppppppppppppppppppppaaammdddddmmaaa',
      'aaaaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqaaammdddddmmaaa',
      'aaaapppppppppppppppppppppppppppppaaammmmmmmmmaaa',
      'aaaaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqaaammmmmmmmmaaa',
      'aaaapppppppppppppppppppppppppppppaaammmmmmmmmaaa',
      'aaaapppppppppppppppppppppppppppppaaammmmmmmmmaaa',
      'tttttttttttttttttttttttttttttttttttttttttttttttt',
      'ssssssssssssssssssssssssssssssssssssssssssssssss',
      '000000000000000000000000000000000000000000000000',
    ],
  },
  laundromat: {
    shell: 'stucco',
    sign: '#4f6337',
    rows: [
      '................................................',
      '................................................',
      '................................................',
      '000000000000000000000000000000000000000000000000',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbabbbbbbbbbbabbbbbbbbbbabbbbbbbbbbabbbbbbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'abbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbba',
      'abbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbba',
      'abbbbbabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbba',
      'abbbbbabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbba',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'gggggggggggggggggggggggggggggggggggggggggggggggg',
      'ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
      'ghhhhhiihhiihhiihhiihhiihhiihhiihhiihhiihhhhhhhg',
      'ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
      'gggggggggggggggggggggggggggggggggggggggggggggggg',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaadddddddddddddaadddddddddddddaammmmmmmmmmmaaaa',
      'aaadddddddddddddaadddddddddddddaammdddddddmmaaaa',
      'aaadddddddddddddaadddddddddddddaammdddddddmmaaaa',
      'aaaddqqqqqddqqqqqadqqqqqddqqqqqaammdddddddmmaaaa',
      'aaaddqqqqqddqqqqqadqqqqqddqqqqqaammdddddddwmaaaa',
      'aaaddqqqqqddqqqqqadqqqqqddqqqqqaammdddddddmmaaaa',
      'aaaddqqqqqddqqqqqadqqqqqddqqqqqaammmmmmmmmmmaaaa',
      'aaadddddddddddddaadddddddddddddaammmmmmmmmmmaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'tttttttttttttttttttttttttttttttttttttttttttttttt',
      'ssssssssssssssssssssssssssssssssssssssssssssssss',
      '000000000000000000000000000000000000000000000000',
    ],
  },
  trucking: {
    shell: 'clapboard',
    sign: '#3d3830',
    rows: [
      '................................................',
      '................................................',
      '................................................',
      '000000000000000000000000000000000000000000000000',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabba',
      'abbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabba',
      'abbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabba',
      'abbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabba',
      'abbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabba',
      'abbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabba',
      'abbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabba',
      'abbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabba',
      'abbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabba',
      'abbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabba',
      'abbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabba',
      'abbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabba',
      'abbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabba',
      'abbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabba',
      'gggggggggggggggggggggggggggggggggggggggggggggggg',
      'ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
      'ghhhhhiihhiihhiihhiihhiihhiihhiihhiihhiihhhhhhhg',
      'ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
      'gggggggggggggggggggggggggggggggggggggggggggggggg',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaappppppppppppppppppppaappppppppppppppppppppaaa',
      'aaaqqqqqqqqqqqqqqqqqqqqaaqqqqqqqqqqqqqqqqqqqqaaa',
      'aaappppppppppppppppppppaappppppppppppppppppppaaa',
      'aaaqqqqqqqqqqqqqqqqqqqqaaqqqqqqqqqqqqqqqqqqqqaaa',
      'aaappppppppppppppppppppaappppppppppppppppppppaaa',
      'aaaqqqqqqqqqqqqqqqqqqqqaaqqqqqqqqqqqqqqqqqqqqaaa',
      'aaappppppppppppppppppppaappppppppppppppppppppaaa',
      'aaaqqqqqqqqqqqqqqqqqqqqaaqqqqqqqqqqqqqqqqqqqqaaa',
      'aaappppppppppppppppppppaappppppppppppppppppppaaa',
      'aaappppppppppppppppppppaappppppppppppppppppppaaa',
      'tttttttttttttttttttttttttttttttttttttttttttttttt',
      'ssssssssssssssssssssssssssssssssssssssssssssssss',
      '000000000000000000000000000000000000000000000000',
    ],
  },
  construction: {
    shell: 'stone',
    sign: '#7d6720',
    rows: [
      '................................................',
      '................................................',
      '................................................',
      '000000000000000000000000000000000000000000000000',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbabbbbbbbbbbabbbbbbbbbbabbbbbbbbbbabbbbbbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbbbbbbaaaaaaaabbbbbbbbbaaaaaaaabbbbbbbbbbba',
      'abbbbbbbbbbannnnnnabbbbbbbbbannnnnnabbbbbbbbbbba',
      'abbbbbbbbbbammmammabbbbbbbbbammmammabbbbbbbbbbba',
      'aaaaaaaaaaaannnnnnaaaaaaaaaaannnnnnaaaaaaaaaaaaa',
      'abbbbbabbbbammmammabbbbbbbbbammmammabbbabbbbbbba',
      'abbbbbabbbbannnnnnabbbbbbbbbannnnnnabbbabbbbbbba',
      'abbbbbabbbbammmammabbbbbbbbbammmammabbbabbbbbbba',
      'aaaaaaaaaaaannnnnnaaaaaaaaaaannnnnnaaaaaaaaaaaaa',
      'abbbbbbbbbbaaaaaaaabbbbbbbbbaaaaaaaabbbbbbbbbbba',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'gggggggggggggggggggggggggggggggggggggggggggggggg',
      'ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
      'ghhhhhiihhiihhiihhiihhiihhiihhiihhiihhiihhhhhhhg',
      'ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
      'gggggggggggggggggggggggggggggggggggggggggggggggg',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbbbbaaaaaaaaaaabbbbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbbbbammmmmmmmmabbbbbbbbbbbbbbbbba',
      'abmnnmnnmnnmnnmnnbbamdddddddmabbbbbbbbbbbbbbbbba',
      'abmnnmnnmnnmnnmnnbbamdddddddmabbbbbbbbbbbbbbbbba',
      'abmnnmnnmnnmnnmnnbbamddddddwmabbbbbbbbbbbbbbbbba',
      'abmnnmnnmnnmnnmnnbbamdddddddmabbbbbbbbbbbbbbbbba',
      'abmnnmnnmnnmnnmnnbbamdddddddmabbbbbbbbbbbbbbbbba',
      'abmnnmnnmnnmnnmnnbbammmmmmmmmabbbbbbbbbbbbbbbbba',
      'abmnnmnnmnnmnnmnnbbammmmmmmmmabbbbbbbbbbbbbbbbba',
      'abmnnmnnmnnmnnmnnbbammmmmmmmmabbbbbbbbbbbbbbbbba',
      'tttttttttttttttttttttttttttttttttttttttttttttttt',
      'ssssssssssssssssssssssssssssssssssssssssssssssss',
      '000000000000000000000000000000000000000000000000',
    ],
  },
  social_club: {
    shell: 'brick',
    sign: '#332a22',
    rows: [
      '................................................',
      '................................................',
      '................................................',
      '000000000000000000000000000000000000000000000000',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbbbbbbaaaaaaaabbbbbbbbbaaaaaaaabbbbbbbbbbba',
      'abbbbbbbbbbaaaaaaaabbbbbbbbbaaaaaaaabbbbbbbbbbba',
      'aaaaaaaaaaaannnnnnaaaaaaaaaaannnnnnaaaaaaaaaaaaa',
      'abbbbbbbbbbammmammabbbbbbbbbammmammabbbbbbbbbbba',
      'abbbbbbbbbbannnnnnabbbbbbbbbannnnnnabbbbbbbbbbba',
      'aaaaaaaaaaaammmammaaaaaaaaaaammmammaaaaaaaaaaaaa',
      'abbbbbbbbbbannnnnnabbbbbbbbbannnnnnabbbbbbbbbbba',
      'abbbbbbbbbbammmammabbbbbbbbbammmammabbbbbbbbbbba',
      'aaaaaaaaaaaannnnnnaaaaaaaaaaannnnnnaaaaaaaaaaaaa',
      'abbbbbbbbbbaaaaaaaabbbbbbbbbaaaaaaaabbbbbbbbbbba',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'aaaaaaaaaaaaaaggggggggggggggggggggaaaaaaaaaaaaaa',
      'abbbbbbbbbbbbbggiiiiiiiiiiiiiwwwwgbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbgggggggggggggggwwwwgbbbbbbbbbbbbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbbbbaaaaaaaaaaabbbbbbbbbbbbbbbbba',
      'abbbbbaaaaaaaaaaabbammmmmmmmmabbbbbbbbbbbbbbbbba',
      'abbbbbakkkkkkkkkabbammmmmmmmmabbbbbbbbbbbbbbbbba',
      'abbbbbakkkkkkkkkabbammmmmmmmmabbbbbbbbbbbbbbbbba',
      'abbbbbakkkkkkkkkabbammmmmmmwmabbbbbbbbbbbbbbbbba',
      'abbbbbadddddddddabbammmmmmmmmabbbbbbbbbbbbbbbbba',
      'abbbbbadddddddddabbammmmmmmmmabbbbbbbbbbbbbbbbba',
      'abbbbbadddddddddabbammmmmmmmmabbbbbbbbbbbbbbbbba',
      'abbbbbaaaaaaaaaaabbammmmmmmmmabbbbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbbbbammmmmmmmmabbbbbbbbbbbbbbbbba',
      'tttttttttttttttttttttttttttttttttttttttttttttttt',
      'ssssssssssssssssssssssssssssssssssssssssssssssss',
      '000000000000000000000000000000000000000000000000',
    ],
  },
  nightclub: {
    shell: 'brick',
    sign: '#c2352b',
    rows: [
      '................................................',
      '................................................',
      '................................................',
      '000000000000000000000000000000000000000000000000',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbba',
      'abbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbba',
      'abbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbba',
      'abbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbba',
      'abbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'gggyggggggggggggggggggggggggggggggggggggggggyggg',
      'gggy0r00gg0r00r00r00r00r00r00r00r00r00gg0r00yggg',
      'gggy0r0wwwwriiiiiiiiiiiiiiiiiiiiiiii0wwwwr00yggg',
      'gggy0r0wwwwrgggggggggggggggggggggggg0wwwwr00yggg',
      'gggyggggggggggggggggggggggggggggggggggggggggyggg',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbaaaaaaaaaaaaaaaabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbammmmmmammmmmmmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbammmmmmammmmmmmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbammmmmmammmmmmmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbammmmmmammmmmwmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbammmmmmammmmmmmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbammmmmmammmmmmmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbammmmmmammmmmmmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbammmmmmammmmmmmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbammmmmmammmmmmmabbbbbbbbbbbbbbba',
      'tttttttttttttttttttttttttttttttttttttttttttttttt',
      'ssssssssssssssssssssssssssssssssssssssssssssssss',
      '000000000000000000000000000000000000000000000000',
    ],
  },
  casino: {
    shell: 'stucco',
    sign: '#7593a8',
    rows: [
      '...000...000...000...000...000...000...000......',
      '000ccc000ccc000ccc000ccc000ccc000ccc000ccc000000',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'cccccccccccccccccccccccccccccccccccccccccccccccc',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'abbggggggggggggggggggggggggggggggggggggggggggbba',
      'aaaggggggggggggggggggggggggggggggggggggggggggaaa',
      'abbggyyggyyggyyggyyggyyggyyggyyggyyggyyggyyggbba',
      'abbggyyggyyggyyggyyggyyggyyggyyggyyggyyggyyggbba',
      'abbggyyggyyggyyggyyggyyggyyggyyggyyggyyggyyggbba',
      'aaaggyyggyyggyyggyyggyyggyyggyyggyyggyyggyyggaaa',
      'abbggyyggyyggyyggyyggyyggyyggyyggyyggyyggyyggbba',
      'abbggyyggyyggyyggyyggyyggyyggyyggyyggyyggyyggbba',
      'abbggyyggyyggyyggyyggyyggyyggyyggyyggyyggyyggbba',
      'aaaggggggggggggggggggggggggggggggggggggggggggaaa',
      'abbggggggggggggggggggggggggggggggggggggggggggbba',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'gggyggggggggggggggggggggggggggggggggggggggggyggg',
      'gggy0zy0z00y00z0yz00zy0z00y00z0yz00zy0z00y00yggg',
      'gggy0z00z0iiiiiiiiiiiiiiiiiiiiiiiiiiiiz00z00yggg',
      'gggy0z00z0ggggggggggggggggggggggggggggz00z00yggg',
      'gggyggggggggggggggggggggggggggggggggggggggggyggg',
      'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbaaaaaaaaaaaaaaaabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbammmmmmammmmmmmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbamdddddaddddddmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbamdddddaddddddmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbamdddddadddddwmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbamdddddaddddddmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbamdddddaddddddmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbammmmmmammmmmmmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbammmmmmammmmmmmabbbbbbbbbbbbbbba',
      'abbbbbbbbbbbbbbbammmmmmammmmmmmabbbbbbbbbbbbbbba',
      'tttttttttttttttttttttttttttttttttttttttttttttttt',
      'ssssssssssssssssssssssssssssssssssssssssssssssss',
      '000000000000000000000000000000000000000000000000',
    ],
  },
};

export const CAR_SPRITES: Record<string, CarSprite> = {
  sedan: {
    fixed: null,
    rows: [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '.....................0000000000000000000000.....................',
      '....................0cccccccccccccccccccccc0....................',
      '...................0cdddddbbdddddddddddddddc0...................',
      '..................0cddddddbbdddddddddddddddb0...................',
      '..................0bddddddbbdddddddddddddddb0...................',
      '..................0bddddddbbdddddddddddddddb0...................',
      '......0000000000000bbbbbbbbbbbbbbbbbbbbbbbbb0000000000000.......',
      '.....0ccccccccccccccccccccccccccccccccccccccccccccccccccc0......',
      '....0ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff0.....',
      '....0ffFbbbbb0000000bbbbbbbbbbbbbbbbbbbbbbb0000000bbbbbrff0.....',
      '....0ffFbbbb00ttttt00bbbbbbbbbbbbbbbbbbbbb00ttttt00bbbbrff0.....',
      '....0ffffff00ttttttt00fffffffffffffffffff00ttttttt00ffffff0.....',
      '.....0aaaaa0ttttftttt0aaaaaaaaaaaaaaaaaaa0ttttftttt0aaaaa0......',
      '.....0aaaaa0tttfffttt0aaaaaaaaaaaaaaaaaaa0tttfffttt0aaaaa0......',
      '......000000ttffFfftt000000000000000000000ttffFfftt000000.......',
      '...........0tttfffttt0...................0tttfffttt0............',
      '...........0ttttftttt0...................0ttttftttt0............',
      '...........00ttttttt00...................00ttttttt00............',
      '........000000ttttt0000000000000000000000000ttttt000000.........',
      '.......0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0........',
    ],
  },
  towncar: {
    fixed: null,
    rows: [
      '................................................................',
      '................................................................',
      '................................................................',
      '......................00000000000000000000000000................',
      '.....................0ccccccccbbcccccccbbccccccc0...............',
      '....................0cddddddddbbdddddddbbdddddddc0..............',
      '...................0cdddddddddbbdddddddbbdddddddb0..............',
      '...................0bdddddddddbbdddddddbbdddddddb0..............',
      '...................0bdddddddddbbdddddddbbdddddddb0..............',
      '..000000000000000000bbbbbbbbbbbbbbbbbbbbbbbbbbbbb0000000000000..',
      '.0cFFFFFFFFFFccccccccccccccccccccccccccccccccccccccccccccccccc0.',
      '0ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff0',
      '0ffFbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbrff0',
      '0ffFbbbbbbb0000000bbbbbbbbbbbbbbbbbbbbbbbbbbbbb0000000bbbbbbrff0',
      '0fffffffff00ttttt00fffffffffffffffffffffffffff00ttttt00ffffffff0',
      '.0bbbbbbb00ttttttt00bbbbbbbbbbbbbbbbbbbbbbbbb00ttttttt00bbbbbb0.',
      '.0aaaaaaa0ttttftttt0aaaaaaaaaaaaaaaaaaaaaaaaa0ttttftttt0aaaaaa0.',
      '.0aaaaaaa0tttfffttt0aaaaaaaaaaaaaaaaaaaaaaaaa0tttfffttt0aaaaaa0.',
      '..00000000ttffFfftt000000000000000000000000000ttffFfftt0000000..',
      '.........0tttfffttt0.........................0tttfffttt0........',
      '.........0ttttftttt0.........................0ttttftttt0........',
      '.........00ttttttt00.........................00ttttttt00........',
      '....00000000ttttt0000000000000000000000000000000ttttt0000000....',
      '...0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0...',
    ],
  },
  wedge: {
    fixed: null,
    rows: [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '...............................00000000000......................',
      '.............................00ccccccccccc000...................',
      '...........................00ccdddddddddddccc0..................',
      '.........................00ccddddddddddddddddc000...............',
      '.......................00ccdddddddddddddddddddccc0000000000.....',
      '...000..........0000000ccddddddddddddddddddddddddcccccccccc0....',
      '..0aaa0..000...0cccccccbbbbbbbbbbbbbbbbbbbb000000000acacarr0....',
      '..0aaa000ccc0000000bbbbbbbbbbbbbbbbbaaaaaa00ttttttt00babarr0....',
      '..0acccccbb00ttttt00bbbbbbbbbbbbbbbbajjjj00ttttttttt00ababb0....',
      '..0bbbbbbb00ttttttt00bbbbbbbbbbbbbbbaaaaa0ttttttttttt0bbbbb0....',
      '..0bbbbbbb0ttttftttt0bbbbbbbbbbbbbbbaaaaa0tttttfttttt0bbbbb0....',
      '..0aaaaaaa0tttfffttt0aaaaaaaaaaaaaaaaaaaa0ttttffftttt0aaaaa0....',
      '..0aaaaaaa0ttffFfftt0aaaaaaaaaaaaaaaaaaaa0tttffFffttt0aaaaa0....',
      '...00000000tttfffttt0000000000000000000000ttttffftttt000000.....',
      '..........0ttttftttt0....................0tttttfttttt0..........',
      '..........00ttttttt00....................0ttttttttttt0..........',
      '.....00000000ttttt0000000000000000000000000ttttttttt00000.......',
      '....0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0......',
    ],
  },
  boxtruck: {
    fixed: null,
    rows: [
      '................................................................',
      '......................000000000000000000000000000000000000000...',
      '.....................0ccccccccccccccccccccccccccccccccccccccc0..',
      '.....................0baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab0..',
      '.....................0baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab0..',
      '.....................0baabbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbbaab0..',
      '.....................0baabbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbbaab0..',
      '......0000000000000000baabbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbbaab0..',
      '.....0ccccccccccccccccbaabbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbbaab0..',
      '.....0bdddddddddddbbbbbaabbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbbaab0..',
      '.....0bdddddddddddbbbbbaabbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbbaab0..',
      '.....0bdddddddddddbbbbbaabbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbbaab0..',
      '....0ffdddddddddddbbbbbaabbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbbaaff0.',
      '....0ffFdddd0000000bbbbaabbbbbbbbbbbbbbbaabb0000000b0000000rff0.',
      '....0ffFbbb00ttttt00bbbaabbbbbbbbbbbbbbbaab00ttttt000ttttt00ff0.',
      '....0ffbbb00ttttttt00bbaaaaaaaaaaaaaaaaaaa00tttttt00ttttttt00f0.',
      '.....0aaaa0ttttftttt0aaaaaaaaaaaaaaaaaaaaa0ttttftt0ttttftttt00..',
      '.....0aaaa0tttfffttt0aaaaaaaaaaaaaaaaaaaaa0tttffft0tttfffttt0...',
      '......00000ttffFfftt00000000000000000000000ttffFff0ttffFfftt0...',
      '..........0tttfffttt0.....................0tttffft0tttfffttt0...',
      '..........0ttttftttt0.....................0ttttftt0ttttftttt0...',
      '..........00ttttttt00.....................00tttttt00ttttttt00...',
      '........00000ttttt000000000000000000000000000ttttt000ttttt00....',
      '.......0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0....',
    ],
  },
  burned: {
    fixed: 'black',
    rows: [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '....................0000000000000000000000000...................',
      '...................0qqqqqqqqqqqqqqqqqqqqqqqqq0..................',
      '...................0qkkkkkkkkkkkkkkkkkkkkkkkq0..................',
      '...................0qkkkkkkkkkkkkkkkkkkkkkkkq0..................',
      '...................0qkkkkkkkkkkkkkkkkkkkkkkkq0..................',
      '.......0000000000000qqqqqqqqqqqqqqqqqqqqqqqqq00000000000........',
      '......0qqqqqqqqqqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqq0.......',
      '......0qqqkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkqqq0.......',
      '......0qqqkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkqqq0.......',
      '......0qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpqqqqqqqqqqqqq0.......',
      '......0qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq0.......',
      '......0qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq0.......',
      '......0qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq0.......',
      '.......0000000000000000000000000000000000000000000000000........',
      '............000000000....................000000000..............',
      '...........0kkkkkkkkk0..................0kkkkkkkkk0.............',
      '...........0kkkkkkkkk0..................0kkkkkkkkk0.............',
      '.........000kkkkkkkkk00000000000000000000kkkkkkkkk0000..........',
      '........0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0.........',
    ],
  },
  unmarked: {
    fixed: 'primer',
    rows: [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '.....................0000000000000000000000.....................',
      '....................0cccccbbccccccccccccccc0.........0..........',
      '...................0cdddddbbdddddddddddddddc0....0..0f0.........',
      '..................0cddddddbbdddddddddddddddb0...0f0.0f0.........',
      '..............00..0bddddddbbdddddddddddddddb0..0f0.0f0..........',
      '.............0ff0.0bddddddbbdddddddddddddddb0..0f00f0...........',
      '......0000000Fff000bbbbbbbbbbbbbbbbbbbbbbbbb0000f0f000000.......',
      '.....0ccccccccffccccccccccccccccccccccccccccccccccccccccc0......',
      '....0ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff0.....',
      '....0ffFbbbbb0000000bbbbbbbbbbbbbbbbbbbbbbb0000000bbbbbrff0.....',
      '....0ffFbbbb00ttttt00bbbbbbbbbbbbbbbbbbbbb00ttttt00bbbbrff0.....',
      '....0ffbbbb00ttttttt00bbbbbbbbbbbbbbbbbbb00ttttttt00bbbbff0.....',
      '.....0aaaaa0ttttftttt0aaaaaaaaaaaaaaaaaaa0ttttftttt0aaaaa0......',
      '.....0aaaaa0tttfffttt0aaaaaaaaaaaaaaaaaaa0tttfffttt0aaaaa0......',
      '......000000ttffFfftt000000000000000000000ttffFfftt000000.......',
      '...........0tttfffttt0...................0tttfffttt0............',
      '...........0ttttftttt0...................0ttttftttt0............',
      '...........00ttttttt00...................00ttttttt00............',
      '........000000ttttt0000000000000000000000000ttttt000000.........',
      '.......0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0........',
    ],
  },
  coupe: {
    fixed: null,
    rows: [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '............................0000000000000000....................',
      '...........................0cccccccccccccccc0...................',
      '..........................0cddddddddddddddddc0..................',
      '.........................0cdddddddddddddddddb0..................',
      '.........................0bdddddddddddddddddb0..................',
      '.........................0bdddddddddddddddddb0..................',
      '.......0000000000000000000bbbbbbbbbbbbbbbbbbb00000000000........',
      '......0ccccccccccccccccccccccccccccccccccccccccccccccccc0.......',
      '.....0ffcccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff0......',
      '.....0ffFbbbb0000000bbbbbbbbbbbbbbbbbbbbbb0000000bbbbbrff0......',
      '.....0ffFfff00ttttt00ffffffffffffffffffff00ttttt00ffffrff0......',
      '.....0ffbbb00ttttttt00bbbbbbbbbbbbbbbbbb00ttttttt00bbbbff0......',
      '......0aaaa0ttttftttt0aaaaaaaaaaaaaaaaaa0ttttftttt0aaaaa0.......',
      '......0aaaa0tttfffttt0aaaaaaaaaaaaaaaaaa0tttfffttt0aaaaa0.......',
      '.......00000ttffFfftt00000000000000000000ttffFfftt000000........',
      '...........0tttfffttt0..................0tttfffttt0.............',
      '...........0ttttftttt0..................0ttttftttt0.............',
      '...........00ttttttt00..................00ttttttt00.............',
      '.........00000ttttt000000000000000000000000ttttt000000..........',
      '........0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0.........',
    ],
  },
  wagon: {
    fixed: null,
    rows: [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '.....................0000000000000000000000000000000............',
      '....................0ccccccbbcccccccccbbcccccccccccc0...........',
      '...................0cddddddbbdddddddddbbddddddddddddc0..........',
      '..................0cdddddddbbdddddddddbbddddddddddddb0..........',
      '..................0bdddddddbbdddddddddbbddddddddddddb0..........',
      '..................0bdddddddbbdddddddddbbddddddddddddb0..........',
      '......0000000000000bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb00000......',
      '.....0cccccccccccccccccccccccccccccccccccccccccccccccccccc0.....',
      '....0ffbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffbbbbff0....',
      '....0ffFbbbbb0000000ffffffffffffffffffffffff0000000ffbbbrff0....',
      '....0ffFbbbb00ttttt00bbbbbbbbbbbbbbbbbbbbbb00ttttt00bbbbrff0....',
      '....0ffffff00ttttttt00ffffffffffffffffffff00ttttttt00ffffff0....',
      '.....0aaaaa0ttttftttt0aaaaaaaaaaaaaaaaaaaa0ttttftttt0aaaaa0.....',
      '.....0aaaaa0tttfffttt0aaaaaaaaaaaaaaaaaaaa0tttfffttt0aaaaa0.....',
      '......000000ttffFfftt0000000000000000000000ttffFfftt000000......',
      '...........0tttfffttt0....................0tttfffttt0...........',
      '...........0ttttftttt0....................0ttttftttt0...........',
      '...........00ttttttt00....................00ttttttt00...........',
      '........000000ttttt00000000000000000000000000ttttt000000........',
      '.......0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0.......',
    ],
  },
  beater: {
    fixed: null,
    rows: [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '.....................0000000000000000000000.....................',
      '....................0cccccbbccccccccccccccc0....................',
      '...................0ddddddbbdddddddddddddddc0...................',
      '..................0cddddddbbdddddddddddddddb0...................',
      '..................0bddddddbbdddddddddddddddb0...................',
      '..................0bddddddbbdddddddddddddddb0...................',
      '......0000000000000bbbbbbbbbbbbbbbbbbbbbbbbb0000000000000.......',
      '.....0ccccccccccccccccacccccccccccccccccccccccccccccccccc0......',
      '....0ffbbbbbbbbbbbbbbbbabbbbbbppppppppbbbbbbbbbbbbbbbbbbff0.....',
      '....0ffFbbbbb0000000bbbbbbbbbbppppppppbbbbb0000000bbbbbrff0.....',
      '....0ffFbbbb00ttttt00bbbbbbbbbppppppppbbbb00ttttt00bbbbrff0.....',
      '....0ffbbbb00ttttttt00bbbbbbbbbbbbbbbbbbb00ttttttt00bbbbff0.....',
      '.....0aaaaa0ttttftttt0aaaaaaaaaaaaaaaaaaa0ttttftttt0aaaaa0......',
      '.....0aaaaa0tttfffttt0aaaaaaaaaaaaaaaaaaa0tttfffttt0aaaaa0......',
      '......000000ttffFfftt000000000000000000000ttffFfftt000000.......',
      '...........0tttfffttt0...................0tttfffttt0............',
      '...........0ttttftttt0...................0ttttftttt0............',
      '...........00ttttttt00...................00ttttttt00............',
      '........000000ttttt0000000000000000000000000ttttt000000.........',
      '.......0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0........',
    ],
  },
  van: {
    fixed: null,
    rows: [
      '................................................................',
      '................................................................',
      '................................................................',
      '........00000000000000000000000000000000000000000000000000......',
      '.......0cccccccccccccccccccccccccccccccccccccccccccccccccc0.....',
      '.......0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb0.....',
      '.......0bddddddddddbaaabbbbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbb0.....',
      '.......0bddddddddddbaaabbbbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbb0.....',
      '.......0bddddddddddbaaabbbbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbb0.....',
      '.......0bddddddddddbaaabbbbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbb0.....',
      '.......0bddddddddddbaaabbbbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbb0.....',
      '......0ffddddddddddbaaabbbbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbff0....',
      '......0ffFbbbbbbbbbbaaabbbbbbbbbbbbbbbbbaabbbbbbbbbbbbbbrff0....',
      '......0ffFbbb0000000aaabbbbbbbbbbbbbbbbbaabb0000000bbbbbrff0....',
      '......0fffff00ttttt00ffffffffffffffffffffff00ttttt00fffffff0....',
      '.......0bbb00ttttttt00abbbbbbbbbbbbbbbbbaa00ttttttt00bbbbb0.....',
      '.......0aaa0ttttftttt0aaaaaaaaaaaaaaaaaaaa0ttttftttt0aaaaa0.....',
      '.......0aaa0tttfffttt0aaaaaaaaaaaaaaaaaaaa0tttfffttt0aaaaa0.....',
      '........0000ttffFfftt0000000000000000000000ttffFfftt000000......',
      '...........0tttfffttt0....................0tttfffttt0...........',
      '...........0ttttftttt0....................0ttttftttt0...........',
      '...........00ttttttt00....................00ttttttt00...........',
      '..........0000ttttt00000000000000000000000000ttttt000000........',
      '.........0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0.......',
    ],
  },
  pickup: {
    fixed: null,
    rows: [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................00000000000000..................................',
      '...............0cccccccccccccc0.................................',
      '..............0cddddddddddddddc0................................',
      '.............0cdddddddddddddddb0................................',
      '.............0bdddddddddddddddb000000000000000000000000000......',
      '.............0bdddddddddddddddb0aaaaaaaaaaaaaaaaaaaaaaaaaa0.....',
      '......00000000bbbbbbbbbbbbbbbbb0aaaaaaaaaaaaaaaaaaaaaaaaaa0.....',
      '.....0cccccccccccccccccccccccccccappppppppppppppppppppppac0.....',
      '....0ffbbbbbbbbbbbbbbbbbbbbbbbbbbappppppppppppppppppppppaff0....',
      '....0ffFbbbb0000000bbbbbbbbbbbbbbapppppppppp0000000ppppprff0....',
      '....0ffFbbb00ttttt00bbbbbbbbbbbbbappppppppp00ttttt00pppprff0....',
      '....0fffff00ttttttt00fffffffffffbaaaaaaaaa00ttttttt00aaaaff0....',
      '.....0aaaa0ttttftttt0aaaaaaaaaaaaaaaaaaaaa0ttttftttt0aaaaa0.....',
      '.....0aaaa0tttfffttt0aaaaaaaaaaaaaaaaaaaaa0tttfffttt0aaaaa0.....',
      '......00000ttffFfftt00000000000000000000000ttffFfftt000000......',
      '..........0tttfffttt0.....................0tttfffttt0...........',
      '..........0ttttftttt0.....................0ttttftttt0...........',
      '..........00ttttttt00.....................00ttttttt00...........',
      '........00000ttttt000000000000000000000000000ttttt000000........',
      '.......0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0.......',
    ],
  },
  hearse: {
    fixed: 'black',
    rows: [
      '................................................................',
      '................................................................',
      '................................................................',
      '..................0000000000000000000000000000000000000.........',
      '.................0ccccccccccccccccccccccccccccccccccccc0........',
      '................0cddddddbfbbbbbbbbbbbbbbbbbbbbbbbbbbbfb0........',
      '...............0cdddddddbfddddaaaaaaaaaaaaaaaaaaaddddfb0........',
      '...............0bdddddddbfddddaaaaaaaaaaaaaaaaaaaddddfb0........',
      '...............0bdddddddbfddddaaaaaaaaaaaaaaaaaaaddddfb0........',
      '...............0bdddddddbfdddddddddddddddddddddddddddfb0........',
      '...0000000000000bbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbfb000000...',
      '..0ffccccccccccccccccccccccccccccccccccccccccccccccccccccccff0..',
      '..0ffFbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbrff0..',
      '..0ffFbbbbb0000000bbbbbbbbbbbbbbbbbbbbbbbbbbbbb0000000bbbbrff0..',
      '..0fffffff00ttttt00fffffffffffffffffffffffffff00ttttt00ffffff0..',
      '...0bbbbb00ttttttt00bbbbbbbbbbbbbbbbbbbbbbbbb00ttttttt00bbbb0...',
      '...0aaaaa0ttttftttt0aaaaaaaaaaaaaaaaaaaaaaaaa0ttttftttt0aaaa0...',
      '...0aaaaa0tttfffttt0aaaaaaaaaaaaaaaaaaaaaaaaa0tttfffttt0aaaa0...',
      '....000000ttffFfftt000000000000000000000000000ttffFfftt00000....',
      '.........0tttfffttt0.........................0tttfffttt0........',
      '.........0ttttftttt0.........................0ttttftttt0........',
      '.........00ttttttt00.........................00ttttttt00........',
      '......000000ttttt0000000000000000000000000000000ttttt00000......',
      '.....0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0.....',
    ],
  },
  stripped: {
    fixed: null,
    rows: [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '............................0000000000000000....................',
      '..........................00cccccccccccccccc0...................',
      '.........................0aaaaaaaaaaaaaaaaaac0..................',
      '.........................0aaaaaaaaaaaaaaaaaab0..................',
      '.........................0aaaaaaaaaaaaaaaaaab0..................',
      '.........................0aaaaaaaaaaaaaaaaaab0..................',
      '.......0000000000000000000bbbbbbbbbbbbbbbbbbb00000000000........',
      '......0ccccccccccccccccccccccc00000000000ccccccccccccccc0.......',
      '.....0ffcccccccccccccccccbbbbb0.........0bbbbbbbbbbbbbbff0......',
      '.....0ffFbbbbbbbbbbbbbbbbbbbbb0.........0bbbbbbbbbbbbbrff0......',
      '.....0ffFbbbbbbbbbbbbbbbbbbbbb0.........0bbbbbbbbbbbbbrff0......',
      '.....0ffbbbbbbbbbbbbbbbbbbbbbb0.........0bbbbbbbbbbbbbbff0......',
      '......0aaaaaaaaaaaaaaaaaaaaaaa0.........0aaaaaaaaaaaaaaa0.......',
      '......0aaaaaaaaaaaaaaaaaaaaaaa0.........0aaaaaaaaaaaaaaa0.......',
      '.......00000000000000000000000...........000000000000000........',
      '.............0000000......................0000000...............',
      '............0ppppppp0....................0ppppppp0..............',
      '............0paaaaap0....................0paaaaap0..............',
      '.........0000ppppppp0000000000000000000000ppppppp00000..........',
      '........0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0.........',
    ],
  },
  cruiser: {
    fixed: 'black',
    rows: [
      '................................................................',
      '................................................................',
      '..........................000000000000..........................',
      '.........................0rrrrriieeeee0.........................',
      '.....................00000rrrrffffeeee000000....................',
      '....................0ccccccbbccccccccccccccc0...................',
      '...................0cddddddbbdddddddddddddddc0..................',
      '..................0cdddddddbbdddddddddddddddb0..................',
      '..................0bdddddddbbdddddddddddddddb0..................',
      '..................0bdddddddbbdddddddddddddddb0..................',
      '......0000000000000bbbbbbbbbbbbbbbbbbbbbbbbbb0000000000000......',
      '.....0ccccccccccccccWWWWWWWWWWWWWWWWWWWWWWWWcccccccccccccc0.....',
      '....0ffbbbbbbbbbbbbbWWWWwwwwwwwwwwwwwwwwWWWWbbbbbbbbbbbbbff0....',
      '....0ffFbbbbb0000000WWWWwwwwwwwwwwwwwwwwWWWW0000000bbbbbrff0....',
      '....0ffFbbbb00ttttt00WWWwwwwwwwwwwwwwwwwWWW00ttttt00bbbbrff0....',
      '....0ffffff00ttttttt00ffffffffffffffffffff00ttttttt00ffffff0....',
      '.....0aaaaa0ttttftttt0aaaaaaaaaaaaaaaaaaaa0ttttftttt0aaaaa0.....',
      '.....0aaaaa0tttfffttt0aaaaaaaaaaaaaaaaaaaa0tttfffttt0aaaaa0.....',
      '......000000ttffFfftt0000000000000000000000ttffFfftt000000......',
      '...........0tttfffttt0....................0tttfffttt0...........',
      '...........0ttttftttt0....................0ttttftttt0...........',
      '...........00ttttttt00....................00ttttttt00...........',
      '........000000ttttt00000000000000000000000000ttttt000000........',
      '.......0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0.......',
    ],
  },
};
