/**
 * City conditions: the world having a bad month independently of you.
 *
 * These are not events with buttons. A condition is a state the whole city is
 * in for a few weeks, it changes the numbers every other system already reads,
 * and it arrives because of something true about the board — a case going to
 * trial, a family bleeding out, too much money moving through fronts.
 *
 * Effects are plain multipliers so a condition never needs a special case in
 * the simulation. A key absent from `effects` is 1.
 */

export type WorldEffectKey =
  /** Operation payouts. */
  | 'payout'
  /** Added to operation success chance, as a fraction. Not a multiplier. */
  | 'successDelta'
  /** Heat generated by everything. */
  | 'heatGain'
  /** Front revenue. */
  | 'businessRevenue'
  /** Laundering capacity. */
  | 'launderCapacity'
  /** How readily the other families act. */
  | 'rivalAggression'
  /** How fast agencies build a case. */
  | 'agencyWork';

export interface WorldConditionDef {
  id: string;
  name: string;
  /** One line for the status strip. */
  summary: string;
  /** The memo body when it arrives. */
  body: string;
  tone: 'good' | 'bad' | 'mixed';
  weight: number;
  durationDays: [min: number, max: number];
  /** Days before this one can come round again. */
  cooldownDays: number;
  effects: Partial<Record<WorldEffectKey, number>>;
  /**
   * What a boss with money can do about it, where there is anything.
   *
   * Every condition shipped with one button reading *"Note it — nothing to
   * decide. Only to work around."* That is honest about most weather and wrong
   * about some of it: a crackdown is people who can be reached, a strike is a
   * union that takes money, federal interest is a bigger name they would rather
   * have. Round 17's three scorers all reported the late game as having nothing
   * left to decide, and the city's largest events were the clearest case —
   * they arrive, they cost you for weeks, and the game asks nothing of you.
   *
   * Absent on the conditions where there genuinely is nothing to be done. A
   * recession is not a thing you buy your way out of, and a good summer does
   * not want ending.
   *
   * The price is the decision, and `payable` keeps it unclickable when the
   * money is not there — which `priced.test.ts` enforces across the whole memo
   * catalogue.
   */
  endEarly?: {
    cost: number;
    label: string;
    /** What buying it out actually buys, in the words a boss would use. */
    hint: string;
  };
  /**
   * What has to be true for this to be possible. Read from a small summary of
   * the board rather than GameState, so this file stays free of simulation
   * imports and stays a config file.
   */
  requires?: (board: WorldBoard) => boolean;
}

/** The handful of facts a condition is allowed to care about. */
export interface WorldBoard {
  day: number;
  heat: number;
  openCases: number;
  /** Highest stage index reached by any open case, 0..8. */
  worstCaseStage: number;
  crewSize: number;
  districtsHeld: number;
  businesses: number;
  /** Any two families currently fighting. */
  warInCity: boolean;
  /** A rival below a third of their starting muscle. */
  bleedingRival: boolean;
  weeklyLaundered: number;
}

/**
 * Chance per day of a new condition arriving, once nothing is running.
 *
 * Tuned down hard from where it started. At one arrival every six weeks the
 * city was in a named condition well over half the time, which stops a
 * condition meaning anything — the modifiers just become the baseline the
 * player tunes around. Roughly one condition a season, running about a month,
 * leaves the ordinary state of the world ordinary.
 */
export const CONDITION_CHANCE_PER_DAY = 0.008;
/** Quiet days between conditions. The city is not always in crisis. */
export const CONDITION_GAP_DAYS = 40;

/** Strength below which a family is visibly finished, for `blood_in_water`. */
export const BLEEDING_BELOW = 22;

export const WORLD_CONDITIONS: WorldConditionDef[] = [
  {
    id: 'crackdown',
    name: 'Citywide crackdown',
    summary: 'Extra patrols everywhere. Everything is louder and harder.',
    body:
      `It started with a photograph on the front page — a body in a doorway on Corio ` +
      `Street, and a commissioner who needed to be seen doing something about it.\n\n` +
      `There are cars on corners that never had cars. Everything you do for the next ` +
      `few weeks is going to be seen by somebody, and everything you do is going to ` +
      `be harder than it was last month.`,
    tone: 'bad',
    weight: 20,
    durationDays: [18, 32],
    cooldownDays: 150,
    /*
     * The teeth are in `agencyWork` and `successDelta`, not in `heatGain`.
     *
     * Heat is clamped at 100, so a multiplier on it is close to free for a
     * player already pinned at the ceiling and a real cost to one keeping it
     * at 30 — exactly backwards for a crackdown. Anything meant to punish
     * being loud has to be expressed somewhere without a ceiling.
     */
    effects: { heatGain: 1.2, successDelta: -0.04, agencyWork: 1.2 },
    endEarly: {
      cost: 28_000,
      label: 'Find out who needs paying',
      hint: 'A commissioner under pressure is still a man with a price',
    },
    requires: (b) => b.heat >= 45 || b.openCases > 0,
  },

  {
    id: 'dock_strike',
    name: 'The docks are shut',
    summary: 'Nothing moves through the port. Goods are scarce and expensive.',
    body:
      `The longshoremen walked out on Tuesday and nobody expects them back before ` +
      `the month is out.\n\n` +
      `Nothing is coming through the port, which means everything already in the ` +
      `city is suddenly worth more than it was. It also means the people who move ` +
      `things for a living are standing around with time on their hands, and men ` +
      `with time on their hands get ideas.`,
    tone: 'mixed',
    weight: 16,
    durationDays: [21, 40],
    cooldownDays: 200,
    effects: { payout: 1.22, businessRevenue: 0.93, successDelta: -0.03 },
    endEarly: {
      cost: 18_000,
      label: 'Settle it with the union',
      hint: 'Somebody has to blink, and it can be you',
    },
  },

  {
    id: 'boom',
    name: 'Money everywhere',
    summary: 'Construction, spending, and nobody counting closely.',
    body:
      `Three towers going up on the north side and a bond issue nobody read. There ` +
      `is more money moving through this city this month than anybody can account ` +
      `for, and a great deal of it is moving through places like yours.\n\n` +
      `Cash is easier to make and easier to explain. It will not last.`,
    tone: 'good',
    weight: 14,
    durationDays: [24, 45],
    cooldownDays: 180,
    effects: { payout: 1.2, businessRevenue: 1.3, launderCapacity: 1.25 },
  },

  {
    id: 'recession',
    name: 'The city is broke',
    summary: 'Nobody is spending. Fronts earn less, desperate men are cheap.',
    body:
      `Two plants closed inside a fortnight and the papers have started using the ` +
      `word properly instead of dancing around it.\n\n` +
      `Legitimate business is not earning what it was. On the other hand there are ` +
      `a great many men in this city right now who would do almost anything for ` +
      `steady money, and you are one of the few people offering any.`,
    tone: 'mixed',
    weight: 15,
    durationDays: [30, 55],
    cooldownDays: 200,
    effects: { businessRevenue: 0.85, launderCapacity: 0.92, payout: 1.05 },
  },

  {
    id: 'sitdown',
    name: 'A sitdown was called',
    summary: 'The families agreed to stop pushing. For now.',
    body:
      `Somebody with more standing than any of you got everyone into the same back ` +
      `room and made it clear that the fighting was costing money and drawing eyes.\n\n` +
      `Nobody signed anything. Nobody had to. For the next few weeks the other ` +
      `families are going to sit very still, and so, if you have any sense, are you.`,
    tone: 'good',
    weight: 14,
    durationDays: [21, 35],
    cooldownDays: 160,
    effects: { rivalAggression: 0.45, heatGain: 0.85 },
    requires: (b) => b.warInCity || b.heat >= 55,
  },

  {
    id: 'federal_interest',
    name: 'Federal interest',
    summary: 'Out-of-town agents, working quietly and well funded.',
    body:
      `The men asking questions this month are not from here. They have better suits ` +
      `and much better records, and they are not interested in a shakedown on ` +
      `Delacroix — they are interested in the shape of the whole thing.\n\n` +
      `Whatever is being built against you is being built faster than it was.`,
    tone: 'bad',
    weight: 12,
    durationDays: [28, 50],
    cooldownDays: 220,
    effects: { agencyWork: 1.3, heatGain: 1.1 },
    endEarly: {
      cost: 45_000,
      label: 'Give them something else to look at',
      hint: 'A bigger name, handed over quietly',
    },
    requires: (b) => b.worstCaseStage >= 3,
  },

  {
    id: 'blood_in_water',
    name: 'Blood in the water',
    summary: 'A family is visibly weak. Everyone is moving.',
    body:
      `One of the families is not what it was a month ago, and everybody in the city ` +
      `can count.\n\n` +
      `Ground that has not changed hands in twenty years is changing hands now. ` +
      `Everyone who has ever wanted a street is reaching for one, which is an ` +
      `opportunity and a very good way to get shot.`,
    tone: 'mixed',
    weight: 13,
    durationDays: [18, 30],
    cooldownDays: 140,
    effects: { rivalAggression: 1.5, heatGain: 1.1 },
    endEarly: {
      cost: 22_000,
      label: 'Put the word out that it is over',
      hint: 'Say it loudly enough and it stops being true',
    },
    requires: (b) => b.bleedingRival,
  },

  {
    id: 'audit_season',
    name: 'They are looking at the books',
    summary: 'Financial scrutiny across the city. Washing money is slow.',
    body:
      `A state examiner with nothing better to do has decided that cash businesses ` +
      `in this city deserve a closer look, and has said so in writing.\n\n` +
      `Every front in the city is being asked for paperwork it does not have. ` +
      `Moving money through them right now is slow, expensive, and extremely visible.`,
    tone: 'bad',
    weight: 12,
    durationDays: [21, 35],
    cooldownDays: 170,
    effects: { launderCapacity: 0.72, agencyWork: 1.1 },
    endEarly: {
      cost: 26_000,
      label: 'Have the paperwork made correct',
      hint: 'Somebody who knows which forms matter',
    },
    requires: (b) => b.businesses >= 2,
  },

  {
    id: 'quiet_summer',
    name: 'A quiet stretch',
    summary: 'Nothing in the papers. Nobody looking anywhere.',
    body:
      `An election, a heatwave, and a scandal at city hall that has nothing to do ` +
      `with anybody you know.\n\n` +
      `Every column inch and every detective in this city is pointed somewhere ` +
      `else. It is the easiest few weeks you are going to get.`,
    tone: 'good',
    weight: 13,
    durationDays: [16, 28],
    cooldownDays: 150,
    effects: { heatGain: 0.78, agencyWork: 0.75, successDelta: 0.04 },
    requires: (b) => b.heat < 70,
  },
];

export const WORLD_CONDITION_BY_ID: Record<string, WorldConditionDef> = Object.fromEntries(
  WORLD_CONDITIONS.map((c) => [c.id, c]),
);
