/**
 * What the city thinks, and what city hall does about it.
 *
 * This is the loop the dependency map was missing. Before it, everything the
 * player did reached law enforcement through one private channel — heat — and
 * the twelve districts, the four agencies and the three families had no
 * audience at all. A war could be fought in the street for two years and the
 * only entity in the simulation that noticed was a case file.
 *
 * Placement matters: this module sits below every system that generates
 * coverage and above none of them. It imports leaf config and territory only,
 * exactly like world.ts, so investigations, diplomacy and operations can all
 * call `cover()` without any of them importing each other.
 */

import { Rng, clamp } from './rng';
import type { CityState, GameState, NewsStory } from './types';
import { addLog, formatMoney } from './util';
import { territoryDef, territoryList } from './territory';
import {
  CITY,
  CITY_INTEL,
  COVERAGE,
  NOTORIETY_BANDS,
  OUTRAGE_BANDS,
  PATRON,
  PRESSURE_BANDS,
  STORIES_PER_DAY,
  STORY_LIMIT,
  type CoverageKind,
} from '../config/perception';
import { PAYDAY_INTERVAL } from '../config/economy';
import { SENTIMENT_START } from '../config/territories';

export function newCity(): CityState {
  return {
    outrage: CITY.outrageBaseline,
    notoriety: 0,
    pressure: 0,
    stories: [],
    lastStoryDay: 0,
    patronUntilDay: null,
  };
}

// -------------------------------------------------------------- coverage ---

interface CoverOptions {
  /** District it happened in, for the headline. */
  territoryId?: string | null;
  /** Person named, where one was. */
  who?: string | null;
  /** True when the organization was identifiably involved. */
  named?: boolean;
  /** Scales prominence — a small clash is not a massacre. */
  scale?: number;
}

/**
 * Something happened that a newspaper would print.
 *
 * Every caller is a system that was already running; none of them needs to
 * know what a headline is. The one rule is that coverage is generated by
 * *events*, never by state — nothing in here reads heat and decides the city
 * is upset, because that would be the private channel again wearing a hat.
 */
export function cover(
  state: GameState,
  rng: Rng,
  kind: CoverageKind,
  options: CoverOptions = {},
): void {
  const def = COVERAGE[kind];
  const scale = options.scale ?? 1;
  const prominence = clamp(def.prominence * scale, 0, 100);
  const named = options.named ?? false;
  const city = state.city;

  city.outrage = clamp(city.outrage + prominence * def.outrage, 0, 100);
  if (named) {
    city.notoriety = clamp(city.notoriety + prominence * def.notoriety, 0, 100);
  }

  // A newspaper has a front page, not a feed. Quiet days stay quiet, and a
  // busy week does not turn into thirty identical lines nobody reads.
  const today = city.stories.filter((s) => s.day === state.day).length;
  if (today >= STORIES_PER_DAY) return;
  if (prominence < 25 && rng.chance(0.5)) return;

  /*
   * Pick a headline that fits what is actually known.
   *
   * A war fought where neither side has ground has no district to name, and
   * the generic substitution produced "Open violence in the city as gangs
   * clash" — which is not how a sub-editor writes. Prefer a template that does
   * not need the missing detail, and only fall back when the pool has nothing
   * else to offer.
   */
  const where = options.territoryId ? territoryDef(options.territoryId)?.name : null;
  const usable = where
    ? def.headlines
    : def.headlines.filter((h) => !h.includes('{where}'));
  const headline = rng
    .pick(usable.length > 0 ? usable : def.headlines)
    .replace('{where}', where ?? 'the city')
    .replace('{who}', options.who ?? 'A man');

  const story: NewsStory = {
    day: state.day,
    headline,
    prominence: Math.round(prominence),
    named,
    tone: def.tone,
  };
  city.stories.unshift(story);
  if (city.stories.length > STORY_LIMIT) city.stories.length = STORY_LIMIT;
  city.lastStoryDay = state.day;

  // Only the loud ones interrupt. The rest are there to be read.
  if (prominence >= 60) {
    addLog(state, `In the papers: ${headline}.`, named ? 'heat' : 'neutral');
  }
}

// ------------------------------------------------------------------ tick ---

/**
 * Weekly. Outrage decays toward a baseline, pressure chases outrage with a
 * lag, and both of them reach out into the districts.
 *
 * The lag is the whole design. A fortnight of fury does nothing, because
 * nobody in an office has moved yet. Two months of it becomes a task force
 * that is still there long after the city has stopped caring.
 */
export function tickPerception(state: GameState, rng: Rng): void {
  if (state.day % PAYDAY_INTERVAL !== 0) return;
  const city = state.city;

  if (city.patronUntilDay !== null && state.day >= city.patronUntilDay) {
    city.patronUntilDay = null;
    addLog(state, 'Your arrangement at city hall has run its course.', 'neutral');
  }

  /*
   * Outrage settles back toward whatever this city considers normal — and what
   * it considers normal is raised by having a frightening organization in it.
   * That floor is how fear reaches the city at all; adding a few points a week
   * could never work, because the weekly decay is larger than any per-week
   * addition small enough not to spiral.
   */
  const toward = clamp(
    CITY.outrageBaseline + (state.org.fear / 100) * CITY.fearFloorAtMax,
    0,
    100,
  );
  const step = Math.min(CITY.outrageDecayPerWeek, Math.abs(city.outrage - toward));
  city.outrage = clamp(city.outrage + (city.outrage > toward ? -step : step), 0, 100);
  city.notoriety = Math.max(0, city.notoriety - CITY.notorietyDecayPerWeek);

  // Political will follows, held back if somebody is being paid to hold it.
  const held = city.patronUntilDay !== null ? PATRON.pressureShare : 1;
  const target = city.outrage * held;
  if (city.pressure < target) {
    city.pressure = clamp(
      city.pressure + (target - city.pressure) * CITY.pressureFollowsOutrage,
      0,
      100,
    );
  } else {
    city.pressure = Math.max(0, city.pressure - CITY.pressureDecayPerWeek);
  }

  // A frightened city is a worse place to live, everywhere at once.
  const drag = (city.outrage / 100) * CITY.sentimentPerWeekAtMax;
  if (drag < 0) {
    for (const t of territoryList(state)) {
      t.sentiment = clamp(t.sentiment + drag, 0, SENTIMENT_START);
    }
  }

  if (city.patronUntilDay !== null && rng.chance(PATRON.exposureChancePerWeek)) {
    city.patronUntilDay = null;
    cover(state, rng, 'corruption', { named: true });
    addLog(
      state,
      'The man you had at city hall is on the front page, and so, by implication, are you.',
      'failure',
    );
  }
}

// ------------------------------------------------------------- readouts ---

/** Multiplier on how fast agencies clear the gate between stages. */
export function pressurePace(state: GameState): number {
  return 1 + (state.city.pressure / 100) * CITY.agencyPaceAtMax;
}

/** Multiplier on how much case strength an agency's own work produces. */
export function pressureWork(state: GameState): number {
  return 1 + (state.city.pressure / 100) * CITY.agencyWorkAtMax;
}

/** Points knocked off every agency's heat floor. Under pressure they reach lower. */
export function pressureHeatFloorDrop(state: GameState): number {
  return (state.city.pressure / 100) * CITY.heatFloorDropAtMax;
}

/** Legitimate business is worse in a city that feels unsafe. */
export function outrageBusinessMultiplier(state: GameState): number {
  return 1 - (state.city.outrage / 100) * (1 - CITY.businessRevenueAtMin);
}

function band(bands: [number, string][], value: number): string {
  return bands.find(([min]) => value >= min)?.[1] ?? bands[bands.length - 1][1];
}

export interface CityRead {
  /** Always available — anybody can buy a newspaper. */
  stories: NewsStory[];
  /** Null when the player has no way of knowing. */
  mood: string | null;
  pressure: string | null;
  notoriety: string | null;
  patron: boolean;
}

/**
 * What the player is allowed to know about the city.
 *
 * Headlines are public, so they are always there. Reading the mood behind them
 * takes somebody who talks to people, and knowing what city hall actually
 * intends takes real pull — which is the first time in this game that the
 * Influence attribute buys information rather than access.
 */
export function readCity(state: GameState): CityRead {
  const influence = state.player.attributes.influence;
  return {
    stories: state.city.stories.slice(0, 12),
    mood: influence >= CITY_INTEL.moodNeedsInfluence ? band(OUTRAGE_BANDS, state.city.outrage) : null,
    pressure:
      influence >= CITY_INTEL.pressureNeedsInfluence
        ? band(PRESSURE_BANDS, state.city.pressure)
        : null,
    notoriety:
      influence >= CITY_INTEL.moodNeedsInfluence
        ? band(NOTORIETY_BANDS, state.city.notoriety)
        : null,
    patron: state.city.patronUntilDay !== null,
  };
}

// ----------------------------------------------------------- counterplay ---

export interface PatronResult {
  ok: boolean;
  message: string;
}

export function canBuyPatron(state: GameState): PatronResult {
  if (state.city.patronUntilDay !== null) {
    return { ok: false, message: 'You already have somebody holding this off.' };
  }
  if (state.player.attributes.influence < PATRON.influenceRequired) {
    return {
      ok: false,
      message: `Nobody at city hall will take the meeting. Needs Influence ${PATRON.influenceRequired}.`,
    };
  }
  if (state.org.cash + state.org.dirtyCash < PATRON.cost) {
    return {
      ok: false,
      message: `Somebody in office costs ${formatMoney(PATRON.cost)} and you hold ${formatMoney(
        state.org.cash + state.org.dirtyCash,
      )}.`,
    };
  }
  return { ok: true, message: 'Find somebody in office' };
}

/**
 * Buying a friend in office.
 *
 * Note what it does not do: it does not reduce outrage. You cannot buy what a
 * city thinks. It holds the political response off the outrage for a season,
 * which is a stranger and better thing to be paying for — and it is itself a
 * story waiting to run.
 */
export function buyPatron(state: GameState): PatronResult {
  const check = canBuyPatron(state);
  if (!check.ok) return check;

  const fromDirty = Math.min(state.org.dirtyCash, PATRON.cost);
  state.org.dirtyCash -= fromDirty;
  state.org.cash -= PATRON.cost - fromDirty;

  state.city.patronUntilDay = state.day + PATRON.days;
  addLog(
    state,
    'There is a man in the building now who takes your calls. Nothing about the city has changed. What the city can do about you has.',
    'crew',
  );
  return { ok: true, message: 'You have somebody in office.' };
}
